[[constraint]]
  branch = "reusable-exec"
  name = "github.com/deislabs/porter"
  source = "github.com/carolynvs/porter"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/PaesslerAG/jsonpath"
  version = "v0.1.1"

[prune]
  go-tests = true
  unused-packages = true
